In [13]:
import tensorflow as tf
import numpy as np
import tifffile as tiff
from tensorflow.keras import backend as K

In [14]:
path = '/data/home/dz/rDL_SIM/SR/Microtubules_result/train/Cell_002_level01_croped000.tif'
img = tiff.imread(path)
img = np.array([img])
img = np.transpose(img, (0, 2, 3, 1)).astype(np.float32)
img = tf.convert_to_tensor(img)

In [15]:
img.shape

TensorShape([1, 128, 128, 9])

In [21]:
def global_average_pooling(input):
    return tf.reduce_mean(input, axis=(1, 2), keepdims=True)

In [22]:
global_average_pooling(img)

<tf.Tensor: shape=(1, 1, 1, 9), dtype=float32, numpy=
array([[[[103.068665, 101.83844 , 101.564575, 101.58099 , 101.7146  ,
          101.60803 , 101.55548 , 101.43646 , 101.44232 ]]]],
      dtype=float32)>

In [20]:
output

<tf.Tensor: shape=(1, 128, 128, 9), dtype=float32, numpy=
array([[[[104., 108.,  97., ..., 100., 101.,  96.],
         [105., 101., 106., ..., 102., 105., 102.],
         [113., 108.,  97., ..., 101., 100., 100.],
         ...,
         [ 99., 103.,  97., ..., 101.,  98., 101.],
         [103.,  98., 101., ...,  98., 101., 103.],
         [100.,  97., 100., ..., 103., 100., 100.]],

        [[105., 101.,  99., ..., 105., 113., 112.],
         [100., 105., 104., ..., 101.,  99.,  99.],
         [ 97., 101.,  98., ..., 101., 103., 101.],
         ...,
         [103., 104., 102., ...,  99., 104., 102.],
         [ 99., 101.,  97., ...,  98., 102., 101.],
         [103., 102.,  99., ...,  99., 103., 102.]],

        [[104.,  97.,  99., ...,  97., 100., 100.],
         [103., 101.,  98., ...,  99.,  99., 102.],
         [101., 102., 103., ...,  97.,  98.,  98.],
         ...,
         [108.,  99., 105., ...,  97., 100.,  97.],
         [105., 105.,  97., ...,  97., 103.,  95.],
         [10

In [12]:
absfft

<tf.Tensor: shape=(1, 9, 128, 128), dtype=float32, numpy=
array([[[[4.1952195, 2.4560616, 2.373661 , ..., 2.1199367, 2.373661 ,
          2.4560616],
         [2.465388 , 2.169074 , 2.1250334, ..., 1.7014279, 2.1689656,
          2.2792304],
         [2.317319 , 2.1172214, 1.9635744, ..., 1.8752217, 2.1043215,
          2.0450282],
         ...,
         [2.136768 , 2.046473 , 1.903327 , ..., 1.8494413, 1.9739505,
          1.8514888],
         [2.3173187, 2.0450282, 2.1043215, ..., 1.7825689, 1.9635744,
          2.1172214],
         [2.4653878, 2.2792304, 2.1689656, ..., 1.897171 , 2.1250334,
          2.169074 ]],

        [[4.190185 , 2.4781747, 2.424647 , ..., 2.1329827, 2.424647 ,
          2.4781747],
         [2.487933 , 2.098214 , 2.1851568, ..., 1.9533027, 2.135967 ,
          2.2914453],
         [2.3514762, 2.0539107, 2.084957 , ..., 1.8923221, 2.1855128,
          2.0818226],
         ...,
         [2.2075408, 1.9813285, 1.9647492, ..., 1.9392741, 1.7540685,
          1.84

In [38]:
diff

<tf.Tensor: shape=(1, 10, 128, 9), dtype=float32, numpy=
array([[[[  1. ,   3. ,   2. , ...,  -1. ,   0. ,   2. ],
         [ -0.5,   2. ,   1.5, ...,   1.5,  -2. ,   1.5],
         [  4. ,  -3. ,   0. , ...,   2. ,   0. ,   2. ],
         ...,
         [  2.5,   1. ,   1. , ...,   0.5,  -5. ,  -1.5],
         [ -5. ,   0. ,  -4. , ...,  -3.5,  -3. ,  -5.5],
         [ -3. ,  -1. ,   4. , ...,   0.5,  -0.5,  -8. ]],

        [[  1.5,   2. ,   0. , ...,   4. ,  -2.5,   5. ],
         [ -1. ,  -2.5,   0. , ...,  -1. ,  -0.5,   1. ],
         [ -1.5,   2. ,  -1. , ...,  -1.5,   6.5,  -1. ],
         ...,
         [ -1.5,  -1. ,  -4. , ...,  -1. ,  -2. ,   2. ],
         [ -7. ,  -3. ,   0. , ...,  -3.5,  -0.5,  -0.5],
         [ -3.5,  -4.5,   1.5, ...,   1.5,   4.5,  -1. ]],

        [[  0. ,   1.5,  -2.5, ...,  -0.5,  -2.5,  -2. ],
         [  4. ,   0.5,   1. , ...,   0.5,  -0.5,   4.5],
         [ -2. ,   5. ,  -1.5, ...,   1.5,   0. ,  -5.5],
         ...,
         [ -2.5,  -2.5,  -5